local_backend: true
backend:
  name: git-gateway
  # name: github
  # name: test-repo
  # branch: main
  branch: main
  repo: annamariasikorska/edce
  site_domain: edce.space
  base_url: https://edce.spac
  auth_endpoint: oauth
  automatic_deployments: true
media_folder: "src/assets/images"
collections:
  - name: "article" # Used in routes, e.g., /admin/collections/blog
    label: "Article" # Used in the UI
    folder: "src/content/article" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "publishDate", widget: "datetime", required: true }
      - { label: "Summary", name: "description", widget: "string", required: false }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Small thumbnail", name: "smallThumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Tags", name: "tags", widget: "list", default: ["news"] }